export const CONVERT_CURRENCY = 'CONVERT_CURRENCY';
export const EXCHANGE_FORM_UPDATE = 'EXCHANGE_FORM_UPDATE';
export const RATES_FETCH_SUCCESS = 'RATES_FETCH_SUCCESS';
export const FETCH_RATES = 'FETCH_RATES';
export const RATES_FETCH_FAILURE = 'RATES_FETCH_FAILURE';
