export const colors ={
    main:'#90BD85',
    second : '#0C6656',
   // listItemHeader:'#F3F0ED',
     listItemHeader:'transparent',
     transparent:'transparent',
    inputBlueBorder:'#9CC8E1',
    facebookBlue : '#3b5998',
    instagramRedLight : '#c32aa3',
    twitterBlue : '#1da1f2',
    white:'white',
    orange:'#d69113',
    whiteShadow:'#F0ECEC',
    whiteGrayed:'#E9E2E2',
    vimto:'#AC1E0E',
    softWhite:'#F6F9F5',
    mainGradient:['#F6F9F5','#BBD2C5'],
    gray:'gray',
    secondGradient:['#90F7EC','#32CCBC']
}